### ISSUE TITLE
Unzip plugins and lay out their directory structure instead?

### ISSUE THREAD

**Issue by keanucz** [n42k/brikkit_plugins#4]
Much easier to send pull requests and whatnot rather than just having to decompile the zip and have more complicatedness

**Comment by n42k** [comment]
Hello Keanu73!

Thanks for your suggestion and accompanying pull request.

I'm not sure I understood correctly. What kind of pull requests are you trying to do? Are you trying to improve others' plugins?

**Comment by keanucz** [comment]
Yes, I'm trying to improve other people's plugins.

**Comment by n42k** [comment]
I'm happy you're willing to help others with their plugins. Unfortunately, I cannot be responsible for whether or not a certain plugin will have your changes. The best place for suggesting them is in the repository of the specific plugin you are trying to improve (see the `packages` file), and not on this repository. They can then accept your changes, and include them into BrikkitPlugins.

I will close this since I don't intend to implement it. If you have any further suggestions or questions regarding this particular issue, we can still talk here.
